name: ff_commons
description: FlutterFlow Commons Package

publish_to: 'none'

version: 1.0.18+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aqui_brazil:
    path: ../../
  collection: 1.19.1
  equatable: 2.0.7
  http: 1.4.0
  mime_type: 1.0.0

flutter:
